sortly/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('users.urls.user_urls' ,namespace="users") ),
    path('',include('users.urls.activity_urls' ,namespace="activity") ),
    path('accounts/', include('allauth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root=  settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root=  settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include('debug_toolbar.urls')),

users/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import F, Count
from django.urls import reverse
from django.utils.text import slugify

import uuid
from django_countries.fields import CountryField

ACTIVITY = (
    ('C' , 'Create'),
    ('U' , 'Update'),
    ('M' , 'Move'),
) 

def validate_type_size(value):
    s = str(value).split('.')
    if s[-1] != 'csv':
        raise ValidationError('Only CSV Files are accepted')
    elif value.size >20_48_000:
        raise ValidationError('File size must be less than 2MB')
    return value

def validate_value(value):
    if value <0:
        raise ValidationError('Please enter value higher than 0')
    return value


class DateToChar(models.Func):
    arity = 2
    function = 'to_char'
    output_field = models.CharField() 


#Abstract class
class CommonFields(models.Model):
    '''
    This is a abstract class inherited by other models 
    '''
    name = models.CharField(max_length=100 , unique= True)
    created = models.DateField(auto_now_add= True)
    updated = models.DateTimeField(auto_now_add= True)

    class Meta:
        abstract = True

class User(AbstractUser):
    '''
    Custom User class
    '''
    mobile = models.BigIntegerField(null=True , blank = True,  unique= True)
    address = models.TextField(null=True , blank = True)
    country = CountryField(null= True, blank = True)
    created = models.DateTimeField(auto_now_add= True)
    id = models.UUIDField(default = uuid.uuid4, primary_key= True, editable= False, unique= True)

    def __str__(self) -> str:
        return self.username.title()

    def get_absolute_url(self):
        return reverse("users:detail",kwargs={'username': self.username})


class Category(models.Model):
    '''
    Folder categories
    '''
    name = models.CharField(max_length=100 , unique= True)
    
    class Meta:
        verbose_name_plural = 'categories'
        ordering = ['name',]
    
    def __str__(self) -> str:
        return self.name.title()
    

class Folder(CommonFields):
    '''
    Folder model to store Items
    '''
    user = models.ForeignKey(User , related_name = 'user' ,on_delete= models.CASCADE)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category,on_delete=models.SET_NULL , null= True)
    id = models.BigAutoField(primary_key=True,editable=False,unique=True)

    class Meta(CommonFields.Meta):
        ordering = ['created','name']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Folder ,self).save(*args , **kwargs)

    def __str__(self) -> str:
        return self.name.title()

    def get_absolute_url(self):
        return reverse('activity:view-folder', kwargs={'slug':self.slug})

    def get_item_count(self):
        return self.item_set.values('name').count()

    def get_item_price(self):
        return sum((item[0]*item[1] for item in self.item_set.values_list('price','quantity'))) 


class Item(CommonFields):
    # TODO: Add tags to filter items by Tags  
    
    id = models.BigAutoField(primary_key=True,editable=False,unique=True)
    folder = models.ForeignKey(Folder,on_delete=models.CASCADE)
    slug = models.SlugField(unique=True)
    quantity = models.IntegerField(default=1, validators=[validate_value])
    price = models.FloatField(default=0,blank=True,validators=[validate_value])
    min_quantity = models.IntegerField(null=True,blank=True)
    alerts = models.BooleanField(default=False,blank=True)
    notes = models.TextField(null= True, blank= True)
    prev_quantity = models.IntegerField(null=True, blank= True,default=0)
 
    class Meta(CommonFields.Meta):
        ordering =['-created',]

    def __init__(self , *args, **kwargs):  
        super(Item,self).__init__(*args, **kwargs)  

    def __str__(self) -> str:
        return self.name.title() + '-' + str(self.id)

    def clean(self):
        if self.alerts and not self.min_quantity:
            raise ValidationError('Please specify low stock quantity(min quantity) to enable alerts')
        return super().clean()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.pk:
            self.prev_quantity = Item.objects.values('quantity').get(id = self.pk)['quantity']
        super(Item ,self).save(*args , **kwargs)    
        
    def get_absolute_url(self):
        return reverse('activity:view_item', kwargs={'slug':self.folder.slug ,'itemslug':self.slug})

    @property
    def get_price(self):
        return self.price * self.quantity


    @classmethod
    def get_low_stock_items(cls):
        return cls.objects.filter(min_quantity__gte = F('quantity'))

    @property
    def is_low(self):
        return self.min_quantity >= self.quantity if self.min_quantity else False


class Transaction(models.Model):
    id = models.UUIDField(default = uuid.uuid4, primary_key= True, editable= False, unique= True)
    date = models.DateField(auto_now_add= True, editable=False)
    user = models.ForeignKey(User,on_delete= models.CASCADE )
    item = models.ForeignKey(Item , on_delete=models.CASCADE,related_name= 'item')
    qty_change = models.IntegerField()
    activity = models.CharField(choices= ACTIVITY , max_length=1)
    notes = models.CharField(max_length=150 , null=True ,blank=True)     

    class Meta:
        ordering = ['-date']

    def __str__(self) -> str:
        return f'{self.item.name} - {self.activity} , {self.date}'


class CsvFiles(models.Model):
    user = models.ForeignKey(User,on_delete= models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to='files', validators= [validate_type_size,])

    class Meta:
        ordering = ['date']

    @property
    def get_url(self):
        return self.file.url


class Stat(models.Model):
    win = models.IntegerField()
    mac = models.IntegerField()
    android = models.IntegerField()
    ios = models.IntegerField()
    others = models.IntegerField() 

users/forms.py
from django.db import models
from django.db.models import fields
from django.forms import ModelForm,ValidationError
from django import forms

from .models import CsvFiles, Item, User


class ProfileForm(ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name','last_name','username',
            'email','mobile','address','country',
        ]
        widgets = {
            'address' : forms.Textarea(attrs={'rows': '6' , 'cols': '10'})
        }


class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = [
            'name' , 'quantity',
            'price' ,'min_quantity',
            'alerts' , 'notes'
        ]
        widgets = {
            'notes' : forms.Textarea(attrs={'rows': '3' , 'cols': '10'})
        }

    def clean_quantity(self):
        if self.cleaned_data['quantity'] <= 0:
            raise ValidationError('Quantity must be greater than 0')
        return self.cleaned_data['quantity']


class ImportForm(ModelForm):
    class Meta:
        model = CsvFiles
        fields = ['file',]

users/views/activity_views.py
from django.http.response import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls.base import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView
from django.views.generic.base import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic.list import ListView
from django.db.models import F,Value,Count,Sum
from django.contrib import messages
from django.conf import settings  
from django.views.decorators.cache import cache_page
from django.core.cache import cache

import csv

from users.forms import ImportForm, ItemForm
from users.utils import validate_imported_data
from ..models import DateToChar, Folder, Item, Transaction

CACHE_TTL = getattr(settings, 'CACHE_TTL')

def fetch_item(folder_slug, item_slug):
    try:
        item = Item.objects.select_related('folder').get(slug = item_slug)
        assert item.folder.slug == folder_slug
        return item
    except:
        raise Http404("No Item found" )


@cache_page(CACHE_TTL)
def home(request):
    return render(request ,'home.html')


class AddFolder(LoginRequiredMixin, CreateView):
    model = Folder
    fields = ['name','category','user']

    def form_valid(self, form):
        temp = form.save(commit = False)
        temp.user = self.request.user
        form.save()
        return super().form_valid(form)



class ListFolders(LoginRequiredMixin,ListView):
    model = Folder
    
    def get_queryset(self):
        return Folder.objects.filter(user = self.request.user).annotate(
            item_count = Count('item'),
            item_price = Sum(F('item__quantity') * F('item__price')) 
            )


class UpdateFolder(LoginRequiredMixin,UpdateView):
    model = Folder
    fields = ['name','category']

    def form_valid(self, form):
        return super().form_valid(form)


class DeleteFolder(LoginRequiredMixin,DeleteView):
    model = Folder

    def get_success_url(self):
        return reverse('activity:folders')


class AddItem(LoginRequiredMixin,CreateView):
    form_class = ItemForm
    template_name = 'users/folder_form.html'

    def dispatch(self, request, *args, **kwargs):
        try:
            slug = self.kwargs.get('slug')
        except:
            raise Http404
        self.folder = get_object_or_404(Folder, slug = slug)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        temp = form.save(commit = False)
        temp.folder = self.folder
        form.save() 
        return HttpResponseRedirect(self.get_success_url())


class ListItem(LoginRequiredMixin,ListView):
    model = Item
    template_name= 'users/users_list.html'

    def get_queryset(self) :
        slug = self.kwargs.get('slug')
        items =  super().get_queryset().select_related('folder').filter(folder__slug = slug)
        if not items:
            raise Http404
        return items

    def get_context_data(self, **kwargs):
        slug = self.kwargs.get('slug')
        kwargs['slug'] = slug
        kwargs['page'] = 'items'
        return super().get_context_data(**kwargs)


class ViewItem(LoginRequiredMixin,DetailView):
    model = Item
    template_name= 'users/user_detail.html'

    def get_object(self, queryset=None):     
        folder_slug = self.kwargs.get('slug') 
        item_slug = self.kwargs.get('itemslug')
        item = cache.get('item' , None)
        print(item)
        if not item:
            item =fetch_item(folder_slug, item_slug)
            cache.set('item' , item)
            print("DB Call")
        else:
            print('Cache')
        self.initial_qty = item.quantity
        return item

    def get_context_data(self, **kwargs) :
        slug = self.kwargs.get('slug')
        kwargs['slug'] = slug
        kwargs['page'] ='items'
        return super().get_context_data(**kwargs)


class UpdateItem(LoginRequiredMixin,UpdateView):
    form_class = ItemForm
    template_name= 'users/update_user.html'

    def get_object(self, queryset=None):
        folder_slug = self.kwargs.get('slug') 
        item_slug = self.kwargs.get('itemslug')
        item =fetch_item(folder_slug, item_slug)
        self.initial_qty = item.quantity
        return item

    def form_valid(self, form):
        self.object = form.save()
        return HttpResponseRedirect(self.get_success_url())


class DeleteItem(LoginRequiredMixin,DeleteView):
    model = Item
    template_name = 'users/folder_confirm_delete.html'

    def get_object(self, queryset=None):
        folder_slug = self.kwargs.get('slug') 
        item_slug = self.kwargs.get('itemslug')
        item =fetch_item(folder_slug, item_slug)
        return item

    def get_success_url(self):
        return reverse('activity:folders')


class TransactionList(LoginRequiredMixin,ListView):
    paginate_by = 5

    def get_queryset(self):
        return  Transaction.objects.select_related('item','user','item__folder').filter(user = self.request.user)


class ExportView(LoginRequiredMixin,View):
    def get(self, request):
        response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': 'attachment; filename="Inventory_summary.csv"'},
        )
        data = Item.objects.all().values_list(
            'name','quantity','price','min_quantity','notes','folder__name'
            ).annotate( 
                date_to_str1 = DateToChar(F('created'),Value('YYYY-MM-DD')),
                date_to_str2 = DateToChar(F('updated'),Value('YYYY-MM-DD'))
            )
        writer = csv.writer(response)
        writer.writerow(['name', 'quantity','price','min_quantity','notes','folder','created','updated'])
        for d in data:
            writer.writerow(d)
        return response


@login_required
def import_items(request):
    form = ImportForm()
    if request.method == 'POST':
        form = ImportForm(request.POST, request.FILES)
        if form.is_valid:
            temp = form.save(commit= False)
            temp.user = request.user
            form.save() 
            a =validate_imported_data(temp.get_url,request)
            if a[0] == 'Success':
                messages.success(request , 'Items Imported Succesfully')
                context = {'count':len(a[1]), 'items':a[1],'page':'report'}
                return render(request,'users/import_form.html',context)
            else:
                messages.error(request , 'Import Failed')
    context ={'form': form,'page':'import'}
    return render(request,'users/import_form.html',context)


@login_required
def dashbord(request):
    low_stock= Item.get_low_stock_items().select_related('folder')
    
    items = Item.objects.select_related('folder').filter(folder__user = request.user).values_list('folder','price','quantity')
    folder_count, price ,quantity= zip(*((f, p*q, q) for f,p,q in items))
    price ,quantity ,folder_count = sum(price), sum(quantity) , len(set(folder_count))
    
    transactions = Transaction.objects.select_related('item','user').annotate(
        fold = F('item__folder__slug')).filter(user = request.user)[:5]
    
    context= {
        'low_stock': low_stock ,'item_count': items.count(),
        'folder_count': folder_count , 'price': price , 
        'transactions': transactions ,'qunatity': quantity
        
    }
    return render(request,'dashboard.html',context)

users/views/user_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render
from django.urls.base import reverse
from django.views.generic import UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView

from ..forms import ProfileForm
from ..models import  User

class UserList(LoginRequiredMixin, ListView):
    template_name = 'users/users_list.html'
    queryset = User.objects.all()

    def get_context_data(self, **kwargs) :
        kwargs['page'] ='users'
        return super().get_context_data(**kwargs)


class UpdateProfile(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = ProfileForm
    template_name = 'users/update_user.html'
    queryset = User.objects.all()
    slug_field = "username"
    slug_url_kwarg = "username"

    def test_func(self):
        return self.request.user.username == self.kwargs.get('username',None)


class Profile(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

    def test_func(self):
        return self.request.user.username == self.kwargs.get('username',None)

    def get_context_data(self, **kwargs) :
        kwargs['page'] ='users'
        return super().get_context_data(**kwargs)


class DeleteProfile(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    
    def test_func(self):
        return self.request.user.username == self.kwargs.get('username',None)

    def get_success_url(self):
        return reverse('activity:')

users/templates/users/folder_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5 mb-5 pt-5 pb-5 ps-3 px-3">
    <form method="post">
        {% csrf_token%}
    Delete folder: {{object}}?
    <input type="submit" class="btn" value="Delete">
</form>
<a class=" btn btn-outline-dark" href="{% url 'activity:view-folder' object.slug%}"> Back </a>
</div>
{% endblock content %}

users/templates/users/folder_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="container mt-5 mb-5 pt-5 pb-5 ps-3 px-3">
    {{object}}
</div>
{% endblock content %}

users/templates/users/folder_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5 mb-5 pt-5 pb-5 ps-3 px-3"
style=" width: 40%;border: groove;" >
<form method="post" >
    {% csrf_token%}
    {{form|crispy}}
    <button type="submit" class="btn btn-outline-dark" style="margin-left: 220px; margin-top: 20px;">Update/Create</button>
</form>
</div>
{% endblock content %}

users/templates/users/folder_list.html
{% extends 'base.html' %}
{% load filtags %}

{% block content %}
<h3 class="mx-4 mt-3">Folders</h3>
<hr/>
<div class="container mt-5 mb-5 pt-5 pb-5 ps-3 px-3">
    <div class="row">
    {% for object in object_list %}
    <div class="card col-3 me-3" style="width: 16rem;">
        <div class="card-body">
            <h5 class="card-title">{{object.name}}</h5>
            <br>
            <p >Items: {{object.item_count}} |
            Price: {{object.item_price}}</p>
            {% if object.item_price > 0%}
            <a href="{% url 'activity:items' object.slug%}" class="card-link" >Open</a>
            {%endif %}
            <a href="{% url 'activity:delete-folder' object.slug%}" class="card-link">Delete</a>
          </div>
    </div>
    {% endfor %}
</div>
</div>

<br/>
<br/>

{% endblock content %}

users/templates/users/import_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="container mt-5 mb-5 pt-3 pb-3 ps-3 px-3" style=" width: 40%;border: groove;">
    {% if page == 'import'%}
    <h4 style="text-align: center;" class="pb-3">  Upload CSV File</h4>
    <p class="text-dark">Please check out this file for reference
        <a class="link text-muted" href="{%static 'images/sample_file.xlsx' %}" download="">Instructions</a></p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token%}
        {{form|crispy}}
        <button type="submit" class="btn btn-outline-dark" style="margin-left: 220px; margin-top: 20px;">Upload</button>
    </form>
    <br>
    <p  class="text-dark"> * Rows with wrong format will be skipped or altered</p>
    {% else %}
    <h4>{{count}} items imported</h4>
    <hr />
    <strong>Report:</strong>
    <table>
        <tr>
            <th class="pe-2">Item Name</th>
            <th class="pe-2">Status</th>
            <th class="pe-2">Message</th>
        </tr>
        {% for item in items %}
        <tr>
            <td class="pe-2">{{item}}</td>
            <td class="pe-2">Imported</td>
            <td class="pe-2">Success</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}
</div>
{% endblock content %}

users/templates/users/transaction_list.html
{% extends 'base.html' %}

{% block content %}
<br/>
<br/>
<h5>&nbsp;Transactions</h5>
<div class="container mt-5 mb-5  pb-5 ps-3 px-3">
    <table class="table table-striped table-dark table-hover table-bordered" style="text-align: center;">
        <thead class=" table-active ">
            <tr>
                <th scope="col">Item</th>
                <th scope="col">Activity</th>
                <th scope="col">Changed Quantity</th>
                <th scope="col">Date</th>
                <th scope="col">Transaction Id</th>
                <th scope="col">Notes</th>
            </tr>
        </thead>
        {% for trans in page_obj %}
            <tr  >
                <th scope="row">
                <a href="{% url 'activity:view_item' trans.item.folder.slug trans.item.slug%}"
                style="text-decoration: none;" class="text-light">
                    {{trans.item}}
                </a>
                </th>
                <td>{{trans.get_activity_display}}</td>
                {% if trans.qty_change > 0 %}
                    <td>+{{trans.qty_change}}</td>
                {% else %}
                    <td>{{trans.qty_change}}</td>
                {% endif %}
                <td>{{trans.date}}</td>
                <td>{{trans.id}}</td>
                <td>{{trans.notes}}</td>
            </tr>
        {% endfor %}
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
        {% if page_obj.has_previous%}
          <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
          <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number }}">&laquo;</a></li>
        {% endif %}
        {% for pg in page_obj.paginator.page_range%}
        {% if pg == page_obj.page_number%}   
            <li class="page-item active"><a class="page-link" href="?page={{pg}}">{{pg}}</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{pg}}">{{pg}}</a></li>
        {%endif%}
        {%endfor%}
        {% if page_obj.has_next%}
          <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">&raquo;</a></li>
          <li class="page-item"><a class="page-link" href="?page={{page_obj.paginator.num_pages}}">Last</a></li>
        {% endif %}
        
        </ul>
      </nav>
</div>
{% endblock content %}

users/templates/users/update_user.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container mt-5 mb-5 pt-5 pb-5 ps-3 px-3"
style=" width: 40%;border: groove;" >
<form method="post" >
    {% csrf_token%}
    {{form|crispy}}
    <button type="submit" class="btn btn-outline-dark" style="margin-left: 220px; margin-top: 20px;">Update</button>
</form>
</div>
{% endblock content %}

users/templates/users/user_detail.html
{% extends 'base.html'%}

{% block content %}
{% if page == 'users'%}
{{object_list}}
{%else%}
<div class="container mt-5 mb-5 pt-5 pb-5 ps-3 px-3">

            <h5 class="card-title">{{object.name.title}} &nbsp;
            {% if object.is_low%}
                <span class="badge bg-danger">Low stock</span> 
            {% endif %}
        </h5>
            <a href="{% url 'activity:update_item' slug object.slug%}" class="card-link" >Update</a>
            <hr/>
            <p>Folder : {{object.folder}} </p>
            <p >Quantity: {{object.quantity}}
            <p>Price: {{object.price}} &nbsp;| &nbsp; Total: {{object.get_price}}</p>
            <p>notes: {{object.notes}}</p>
            <p>Alerts: {{object.alerts}} &nbsp;| &nbsp;Min quantity: {{object.min_quantity}}</p>
            <a href="{% url 'activity:update_item' slug object.slug%}" class="card-link" >Update</a>
            <a href="{% url 'activity:delete_item'  slug object.slug%}" class="card-link">Delete</a>

</div>

{% endif %}
{% endblock content %}

users/templates/users/users_list.html
{% extends 'base.html'%}

{% block content %}
{% if page == 'users'%}
{{object_list}}
{%else%}
<h3 class="mx-4 mt-3">Items</h3>
<a class="mx-4" href= "{% url 'activity:add_item' slug %}">Add Item</a>
<hr/>
<div class="container  mb-5 pt-2 pb-5 ps-3 px-3">
    <div class="row">
    {% for object in object_list %}
    <div class="card col-3 me-3 mt-3" style="width: 13rem;">
        <div class="card-body">
            <h5 class="card-title">{{object.name.title}}
            {% if object.is_low%}
                <span class="badge bg-danger">Low stock</span> 
            {% endif %}
            </h5>
            <a href="{% url 'activity:update_item' slug object.slug%}" class="card-link" >Update</a>
            <br>
            <p >Quantity: {{object.quantity}}
            <p>Price: {{object.price}}</p>
            <p>Total: {{object.get_price}}</p>
            <a href="{% url 'activity:view_item' slug object.slug%}" class="card-link" >View</a>
            <a href="{% url 'activity:delete_item'  slug object.slug%}" class="card-link">Delete</a>
            
          </div>
    </div>
    {% endfor %}
</div>
</div>

<br/>
<br/>

{% endif %}
{% endblock content %}